### ISSUE TITLE
No touchpad on Yoga C630

### ISSUE THREAD

**Issue by NiQ1** [aarch64-laptops/build#7] opened 2019-06-19 17:31 UTC
Touchpad does not seem to be working on Lenovo Yoga C630 even though the documentation says it does.
If someone actually got it to work please provide the necessary information, if it's not working let's at least correct the documentation.

**Comment by rhenwood-arm** [comment] 2019-06-19 18:04
@NiQ1 : I have heard reports of the touchpad not working. Can you verify that it is enabled using the F6 hotkey.

Also, can you share which version of the firmware the BIOS reports you have?

**Comment by NiQ1** [comment] 2019-06-19 19:40
Maybe I'm doing something wrong because F6 does nothing (nothing shows up on screen).

BIOS reports:
BIOS Version 9UCN23WW (V1.06)
EC Version 9UCN23WW (V1.06)
Touch Panel Version 24850

Also output of xinput list:
root@ubuntu:~# xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ hid-over-i2c 04F3:2800                  	id=6	[slave  pointer  (2)]
⎜   ↳ HID 04b3:310b                           	id=8	[slave  pointer  (2)]
⎜   ↳ hid-over-i2c 6243:0001 Consumer Control 	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ hid-over-i2c 04F3:2800                  	id=7	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ hid-over-i2c 6243:0001 Keyboard         	id=10	[slave  keyboard (3)]
    ↳ hid-over-i2c 6243:0001 Wireless Radio Control	id=12	[slave  keyboard (3)]
    ↳ pm8941_pwrkey                           	id=13	[slave  keyboard (3)]
    ↳ hid-over-i2c 6243:0001 Consumer Control 	id=14	[slave  keyboard (3)]
root@ubuntu:~# 
(note: 04b3:310b is a USB mouse I'm using)

**Comment by rhenwood-arm** [comment] 2019-06-19 20:14
Thanks for this info. There have been reports of this problem - so you may not be doing anything wrong!

Also, I you haven't already you should try F6 with the 'Fn' key pressed and unpressed.

I don't have access to my machine now, but will hopefully compare info tomorrow.

**Comment by NiQ1** [comment] 2019-06-19 20:38
Tried it with Fn as well of course.
Btw, this is logged when the system boots -
_[FAILED] Failed to start Load Kernel Modules.
See 'systemctl status systemd-modules-load.service' for details._
Not sure whether this is related.

**Comment by lag-linaro** [comment] 2019-06-20 07:12
With regards to the modules, what does `lsmod` return?

**Comment by lag-linaro** [comment] 2019-06-20 07:35
Could you also provide us with a copy of your ACPI tables please?

1. Boot into Windows
2. Download ACPI ‘Windows Binary Tools’ (*.zip file) from [HERE](https://acpica.org/downloads/binary-tools)
4. Open the *.zip file and extract the binaries somewhere accessible (e.g. Documents) 
5. Open a Command prompt (Windows-key + r, type ‘cmd’ and hit return)
6. Change into directory containing the binaries (e.g. `cd Documents/acpitools`)
7. Dump tables to binary files (`acpidump -b`)
8. Binary representations of the tables should appear as *.dat files
9. Disassemble to clear text (*.dsl) files (`iasl -d dsdt.dat`)

Could you then paste the clear text version somewhere public please?

**Comment by NiQ1** [comment] 2019-06-20 07:36
OK let's start with the Linux part -

uname -a
Linux ubuntu 5.0.1-laptops0.1-generic #3-Ubuntu SMP Wed Mar 13 09:45:52 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

lsmod
Module                  Size  Used by
uvcvideo              106496  0
videobuf2_vmalloc      20480  1 uvcvideo
videobuf2_memops       20480  1 videobuf2_vmalloc
videobuf2_v4l2         28672  1 uvcvideo
videobuf2_common       57344  2 videobuf2_v4l2,uvcvideo
videodev              290816  3 videobuf2_v4l2,uvcvideo,videobuf2_common
media                  53248  4 videodev,videobuf2_v4l2,uvcvideo,videobuf2_common
cdc_ether              20480  0
usbnet                 49152  1 cdc_ether
r8152                  65536  0
pm8941_pwrkey          20480  0
qcom_spmi_temp_alarm    16384  0
industrialio           81920  1 qcom_spmi_temp_alarm
qcom_tsens             24576  0
qcom_pon               16384  0
qcom_hwspinlock        16384  1
smp2p                  16384  0
reboot_mode            16384  1 qcom_pon
smem                   16384  1 smp2p
joydev                 32768  0
input_leds             16384  0
hid_multitouch         24576  0
reset_qcom_pdc         16384  0
qcom_rng               16384  0
qcom_cpufreq_hw        20480  0
uio_pdrv_genirq        16384  0
uio                    20480  1 uio_pdrv_genirq
sch_fq_codel           20480  2
ib_iser                49152  0
rdma_cm                65536  1 ib_iser
iw_cm                  49152  1 rdma_cm
ib_cm                  65536  1 rdma_cm
ib_core               270336  4 rdma_cm,iw_cm,ib_iser,ib_cm
iscsi_tcp              24576  0
libiscsi_tcp           32768  1 iscsi_tcp
libiscsi               65536  3 libiscsi_tcp,iscsi_tcp,ib_iser
sunrpc                393216  1
scsi_transport_iscsi   122880  5 libiscsi_tcp,iscsi_tcp,ib_iser,libiscsi
ppdev                  24576  0
lp                     20480  0
parport                53248  2 lp,ppdev
ip_tables              32768  0
x_tables               45056  1 ip_tables
autofs4                53248  2
btrfs                1302528  0
zstd_compress         159744  1 btrfs
raid10                 61440  0
raid456               180224  0
async_raid6_recov      24576  1 raid456
async_memcpy           20480  2 raid456,async_raid6_recov
async_pq               20480  2 raid456,async_raid6_recov
async_xor              20480  3 async_pq,raid456,async_raid6_recov
async_tx               20480  5 async_pq,async_memcpy,async_xor,raid456,async_raid6_recov
xor                    20480  2 async_xor,btrfs
xor_neon               16384  1 xor
raid6_pq              110592  4 async_pq,btrfs,raid456,async_raid6_recov
libcrc32c              16384  2 btrfs,raid456
raid1                  49152  0
raid0                  24576  0
multipath              24576  0
linear                 20480  0
qcom_glink_rpm         16384  0
qcom_glink_native      28672  1 qcom_glink_rpm
qcom_smd_regulator     36864  0
smd_rpm                16384  1 qcom_smd_regulator
rpmsg_core             16384  2 smd_rpm,qcom_glink_native
usbhid                 61440  0
uas                    24576  0
usb_storage            73728  3 uas
aes_ce_blk             28672  0
hid_generic            16384  0
aes_ce_cipher          16384  1 aes_ce_blk
xhci_plat_hcd          20480  0
pinctrl_spmi_gpio      24576  0
rtc_pm8xxx             20480  1
crct10dif_ce           16384  1
dwc3                  155648  0
qcom_spmi_pmic         20480  0
ulpi                   20480  1 dwc3
i2c_hid                32768  0
regmap_spmi            16384  1 qcom_spmi_pmic
udc_core               61440  1 dwc3
hid                   139264  4 i2c_hid,usbhid,hid_multitouch,hid_generic
ghash_ce               20480  0
spmi_pmic_arb          28672  0
sha2_ce                16384  0
spmi                   32768  3 spmi_pmic_arb,regmap_spmi,qcom_spmi_pmic
ufs_qcom               24576  0
ufshcd_pltfrm          20480  1 ufs_qcom
sha256_arm64           24576  1 sha2_ce
dispcc_sdm845          24576  0
sha1_ce                16384  0
ufshcd_core           167936  2 ufs_qcom,ufshcd_pltfrm
gpucc_sdm845           20480  0
nvmem_qfprom           16384  2
dwc3_qcom              20480  0
i2c_qcom_geni          24576  0
videocc_sdm845         20480  0
phy_qcom_qusb2         24576  4
phy_qcom_qmp           28672  5
qcom_apcs_ipc_mailbox    16384  4
aes_neon_bs            24576  1
aes_neon_blk           28672  1 aes_neon_bs
crypto_simd            16384  3 aes_neon_bs,aes_ce_blk,aes_neon_blk
cryptd                 28672  1 crypto_simd
aes_arm64              16384  5 aes_neon_bs,aes_ce_cipher,ghash_ce,aes_ce_blk,aes_neon_blk

Should be noted that the keyboard is also hid-i2c and it does work.

**Comment by lag-linaro** [comment] 2019-06-20 07:51
Well I know for a fact that the latest image does work on my device.

So we need to figure out how your device is different.

The ACPI tables should help.

**Comment by NiQ1** [comment] 2019-06-20 08:05
Here you go

[dsdt.zip](https://github.com/aarch64-laptops/build/files/3309381/dsdt.zip)

**Comment by lag-linaro** [comment] 2019-06-20 08:08
Odd.  Only the serial number is different.  The I2C addresses are the same.

Could you please paste your `dmesg`?

**Comment by lag-linaro** [comment] 2019-06-20 08:09
Could you also paste your `/boot/laptop.dtb` please?

**Comment by NiQ1** [comment] 2019-06-20 08:17
Here you go

[dmesg_and_dtb.zip](https://github.com/aarch64-laptops/build/files/3309440/dmesg_and_dtb.zip)

**Comment by lag-linaro** [comment] 2019-06-20 08:47
So your keyboard was found and should be working:

`input: hid-over-i2c 6243:0001 Keyboard as /devices/platform/soc/ac0000.geniqup/a8c000.i2c/i2c-11/11-005c/0018:6243:0001.0002/input/input6`

As to why your touchpad hasn't been found, I'm at a loss.

I'm using the same kernel and the same DTB as you and it works on my machine.

I assume both work well in Windows?

**Comment by NiQ1** [comment] 2019-06-20 08:56
Yes, keyboard is working, which is why it was weird in the first place because I've noticed that both are hid-i2c so why is one working and not the other...
Both work in Windows of course, otherwise I would have already filed a warranty claim :)

If it makes any difference I didn't use the flash-prebuilt.sh script (instead just used dd and manually linked the DTB), though I doubt it could be the reason since the system does boot.

**Comment by lag-linaro** [comment] 2019-06-20 10:38
What if the MD5 of the image you're using?

Can you please try re-flashing using the `flash-prebuilt.sh` please?

**Comment by NiQ1** [comment] 2019-06-20 11:32
b3c38c31e0a300674feddd26f54f12a2  aarch64-laptops-bionic-prebuilt.img.xz
Originally I tried to save some time by flashing directly from my NAS, where dd is symlinked to busybox so the flash-prebuilt.sh script couldn't run. Flashed again, properly this time, but unfortunately the result is the same.

**Comment by lag-linaro** [comment] 2019-06-20 12:14
I'm flabbergasted.

The ACPI tables are the same, the image is the same.  Not sure what else to suggest TBH.

**Comment by lag-linaro** [comment] 2019-06-20 12:24
Okay try this.

Download and install [THIS PACKAGE](http://people.linaro.org/~lee.jones/linux-image-5.1.0+_5.1.0+-248_arm64.deb).

Then change the 'linux' command in Grub to include `acpi=force` after the kernel image name.

It should look something like this: 

`linux   /boot/vmlinuz-5.0.1-laptops0.1-generic acpi=force root=UUID=c8173430-f081-43b0-bd80-3982d45fc629 ro   efi=novamap ignore_loglevel clk_ignore_unused pd_ignore_unused console=tty0`

To break into Grub press `Esc` on boot.  Then to edit the menu item press `e`.

**Comment by NiQ1** [comment] 2019-06-20 15:36
With acpi=force the system can't find the root filesystem and I'm dropped into initramfs shell with the following error -
_Gave up waiting for the root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
    - Check rootdelay= (did the system wait long enough?)
  - Missing modules (cat /proc/modules: ls /dev)
ALERT! UUID=c8173430-f081-43b0-bd80-3982d45fc629 does not exist.  Dropping to a shell!_

At this point /dev/sdg (the device to which the USB stick is usually mapped) indeed does not exist.
Note that the new kernel does boot without acpi=force (in which case the touchpad doesn't work).

**Comment by lag-linaro** [comment] 2019-06-20 22:40
Which USB port were you plugged into?

Has to be the left one.

**Comment by NiQ1** [comment] 2019-06-21 08:28
Yes, I was using the right one. Touchpad works! It also got the battery meter working as well.

If you have the time I'm interested in how my system was different from yours. It should also be documented somehow that the Yoga C630 should be booted from the left USB port only.

(btw I know it's not related but sound's not supported yet right?)

Thank you for your hard work!

**Comment by lag-linaro** [comment] 2019-06-21 10:14
This isn't a fix per say.  DT is still the best way to boot the platform.

We really need to find out why the touchpad DT isn't working on your device.

Can you paste your `dmesg` on a working boot please?

**Comment by NiQ1** [comment] 2019-06-21 11:49
Here you go,
BTW just noticed that even with acpi=force right click still doesn't work (behaves like left click).

[dmesg_working.zip](https://github.com/aarch64-laptops/build/files/3314297/dmesg_working.zip)

**Comment by RussianNeuroMancer** [comment] 2019-08-04 05:16
For statistic: on my C630 unit touchpad is working.

BIOS: 9UCN33WW (V2.06)
EC Version: 9UEC33WW (V2.06)

[dsdt.zip](https://github.com/aarch64-laptops/build/files/3464556/dsdt.zip)

**Comment by lag-linaro** [comment] 2019-08-06 08:51
I have managed to acquire a laptop with a non-working touchpad.

Watch this space.

**Comment by lag-linaro** [comment] 2019-08-07 08:56
Looks like this is a Device Tree issue.

It's still unclear why this effects some laptops, but not others, but updating should fix it.

Can the OP please respond?

**Comment by dtischler** [comment] 2019-08-09 23:05
Just as an FYI, while at an event this week, @rhenwood-arm helped me to install Ubuntu on my C630, and I experienced this same behavior, non-functional touchpad.  I will keep an eye on this thread as well, for any DT (or other) fixes that come along.

**Comment by lag-linaro** [comment] 2019-08-12 05:43
@dtischler updating will fix the issue.  Unfortunately, that's currently non-trivial due to a version semantics changed a little while back.  A new Bionic (and hopefully Disco) installer(s) are on the way, so this issue will just 'go away' but you will be presented with a choice.  The easiest, but also most risky route is to remove all kernel packages, then (BEFORE REBOOTING) re-install the new ones.  This will fix your issue.

**Comment by dtischler** [comment] 2019-08-12 18:14
Actually, I just nuked my install doing exactly what Richard told me not to do: updating the packages without pinning Grub.  (Well, I **thought** I pinned it properly...but my system now hangs upon attempting to boot.)

So, I will wait patiently for the new installer.

Thanks!

**Comment by rhenwood-arm** [comment] 2019-08-12 18:39
I have just attempted an 'apt uprade' on my bionic C630 which has a non-functional touchpad and it seems to get a bit wrapped up:

```~# 
root@ubuntu-Lenovo-YOGA-C630-13Q50:~# apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  grub-common grub-efi-arm64 grub-efi-arm64-bin grub2-common libdrm-freedreno1 libllvm7 os-prober
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  linux-modules-5.2.0-99-generic
The following NEW packages will be installed
  linux-modules-5.2.0-99-generic
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
4 not fully installed or removed.
Need to get 0 B/12.3 MB of archives.
After this operation, 69.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 162348 files and directories currently installed.)
Preparing to unpack .../linux-modules-5.2.0-99-generic_5.2.0-99.5laptops1_arm64.deb ...
Unpacking linux-modules-5.2.0-99-generic (5.2.0-99.5laptops1) ...
dpkg: error processing archive /var/cache/apt/archives/linux-modules-5.2.0-99-generic_5.2.0-99.5laptops1_arm64.deb (--unpack):
 trying to overwrite '/boot/laptop-asus-tp370ql.dtb', which is also in package linux-modules-5.0.1-laptops0.1-generic 5.0.1-laptops0.1.3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/linux-modules-5.2.0-99-generic_5.2.0-99.5laptops1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@ubuntu-Lenovo-YOGA-C630-13Q50:~``

**Comment by dtischler** [comment] 2019-08-12 20:48
Mine hung indefinitely while doing the upgrade...I never even made it to that error.  I had to forcefully power off and power on, which is most likely the reason mine will no longer boot.

**Comment by lag-linaro** [comment] 2019-08-13 12:13
> I have just attempted an 'apt uprade' on my bionic C630 which has a non-functional touchpad and it seems to get a bit wrapped up:

> dpkg: error processing archive /var/cache/apt/archives/linux-modules-5.2.0-99-generic_5.2.0-99.5laptops1_arm64.deb (--unpack):
>  trying to overwrite '/boot/laptop-asus-tp370ql.dtb', which is also in package linux-modules-5.0.1-laptops0.1-generic 5.0.1-laptops0.1.3

Right. This was the issue I mentioned before.

It's due to a semantic change in the Debian version number.

To fix it, you have to remove all of the laptops kernels and reinstall the newest one.

```
$ sudo apt remove *5.0.1-laptops* *5.2.0-99* linux-generic linux-headers-generic linux-image-generic
$ sudo apt install linux-generic
```

**Comment by lag-linaro** [comment] 2019-08-13 12:14
> Mine hung indefinitely while doing the upgrade...I never even made it to that error. I had to forcefully power off and power on, which is most likely the reason mine will no longer boot.

I've never seen that before.  Doesn't sound like an issue related to this project.

**Comment by dtischler** [comment] 2019-08-13 13:49
The precise location my upgrade stalled was due to Snap, which is now documented in https://github.com/aarch64-laptops/build/issues/19

I didn't think to kill it, as Richard did, so I powered off / on, thus leaving me in the non-funtional state.  However, Richard helped me get back up and running with a quick Grub fix, so today I will re-attempt this upgrade.

Just to clarify, to resolve the Touchpad issue, this is the fix??

`sudo apt remove *5.0.1-laptops* *5.2.0-99* linux-generic linux-headers-generic linux-image-generic
sudo apt install linux-generic`

**Comment by lag-linaro** [comment] 2019-08-13 15:21
> Just to clarify, to resolve the Touchpad issue, this is the fix??

So you should upgrade.  It will appear to fail with the message @rhenwood-arm reported.

At which point you should issue those commands.

Alternatively you could *test* the newly created installer:

https://pskov.surgut.co.uk/bionic/daily-live/20190809.1/

**Comment by dtischler** [comment] 2019-08-13 16:58
Quick update, I have now upgraded kernel to 5.2.0.99 and the rootfs to Disco...but still no Touchpad!  I can certainly attempt that newer image you pointed to if you think that's the way to go.

Here is my current system, with the non-functional Touchpad:

```
david@yogac630:~$ uname -a
Linux yogac630 5.2.0-99-generic #5laptops1-Ubuntu SMP Wed Jul 17 17:08:48 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
david@yogac630:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

Thanks!

**Comment by RussianNeuroMancer** [comment] 2019-08-13 17:21
@dtischler could you please try to boot https://pskov.surgut.co.uk/bionic/daily-live/20190809.1/ from usb stick just for test?

**Comment by dtischler** [comment] 2019-08-13 18:41
I sure can...but...if will need to wait until tomorrow, when a native USB-C flash drive arrives.  I only have "regular" USB3 drives on hand, and when Richard and I first attempted to flash my device via a standard USB3 thumb drive attached via a USB-C hub, it failed to recognize the drive and would not boot.  Already ordered the USB-C drive, should have it tomorrow, and I'll report back.

**Comment by lag-linaro** [comment] 2019-08-14 06:24
Booting from an external hub does not work, but you can boot any (most) USB stick(s) using a USB-C -> USB-A adaptor.

**Comment by lag-linaro** [comment] 2019-08-14 06:26
> I have now upgraded kernel to 5.2.0.99 and the rootfs to Disco...but still no Touchpad

Could you please send me the DTB you are using?

**Comment by lag-linaro** [comment] 2019-08-14 06:27
If the new installer's mouse does not work - it might be a case of updating Windows.

**Comment by dtischler** [comment] 2019-08-14 18:53
Ok, the new USB-C drive arrived, I wrote the image you pointed me to, and booted successfully from the USB drive.  The Touchpad works throughout the installer and even the Live image.  I refrained from installing to the hard drive for now, powered down, and I am currently back in my Disco installation.  From here, I have dumped out the .dtb as you requested, thanks!

[lenovo-yoga-c630.txt](https://github.com/aarch64-laptops/build/files/3502803/lenovo-yoga-c630.txt)

**Comment by lag-linaro** [comment] 2019-08-14 20:28
And '/boot/grub/grub.cfg' please.

**Comment by dtischler** [comment] 2019-08-14 20:51
Attached!

[grub.txt](https://github.com/aarch64-laptops/build/files/3503311/grub.txt)

**Comment by lag-linaro** [comment] 2019-08-14 21:02
Thanks.

`ls -l /boot` please.

**Comment by dtischler** [comment] 2019-08-14 21:17
I think this tells the story, if I understand correctly...Looks like the .dtb symlinks are pointing to the 5.0.1 version.

[ls-boot.txt](https://github.com/aarch64-laptops/build/files/3503394/ls-boot.txt)

**Comment by lag-linaro** [comment] 2019-08-15 06:33
> I think this tells the story, if I understand correctly...Looks like the .dtb symlinks are pointing to the 5.0.1 version.

You got it.

So change the symlink to point to the correct DTB and touchpad should start working. :+1:

**Comment by lag-linaro** [comment] 2019-08-15 08:51
Once you've tested it working, I'd like to call this one done. :smiley:

**Comment by dtischler** [comment] 2019-08-15 15:23
Confirmed and functional!  Thanks so much!

```
rm /boot/dtb
ln -s /boot/laptop-lenovo-yoga-c630.dtb /boot/dtb 
```

Close it out!    :-)

**Comment by lag-linaro** [comment] 2019-08-15 15:36
Great.  Thanks for testing.

**Closed by lag-linaro** 2019-08-15 15:36 UTC

**Comment by NiQ1** [comment] 2019-08-16 10:01
> 
> 
> Great. Thanks for testing.

Hi, sorry I haven't had time to reply for so long. Works for me as well. Out of curiosity I'd appreciate it if you could elaborate what was the problem.

Another issue - When I used acpi=force (before the update was available) it also got the battery meter working. The update does not fix that. Should I open a new issue for that?

**Comment by RussianNeuroMancer** [comment] 2019-08-16 13:15
@NiQ1 battery status reading [works for me with 5.3rc1 kernel](https://github.com/aarch64-laptops/build/issues/11#issuecomment-519209569) ([how to setup](https://github.com/aarch64-laptops/build/issues/13)) on eoan. Be aware thought that many features such as USB Audio, WiFi and others is disabled in 5.3rc1 binary build.

**Comment by dmelgar** [comment] 2019-09-02 01:09
Having this same problem with this repo today 9/1/2019. 
I've tried to follow this thread but nothing I tried work to get the trackpad working. 

`sudo apt remove *5.0.1-laptops* *5.2.0-99* linux-generic linux-headers-generic linux-image-generic
sudo apt install linux-generic`

caused a bunch of errors. Rebooted, still no trackpad.

**Comment by RussianNeuroMancer** [comment] 2019-09-02 02:46
@dmelgar did you tested fresh pre-build images?

**Comment by lag-linaro** [comment] 2019-09-02 07:11
@dmelgar please provide the output of the following commands:

```
$ uname -a
$ ls -l /boot
```

**Comment by dmelgar** [comment] 2019-09-02 19:38
#Current build. Run through install instructions. Using flash-prebuilt.sh lenovo-yoga-c630  #....


[boot.txt](https://github.com/aarch64-laptops/build/files/3566999/boot.txt)
[uname.txt](https://github.com/aarch64-laptops/build/files/3567000/uname.txt)

**Comment by dmelgar** [comment] 2019-09-02 19:42
After clean boot says there's 273MB of updates. Try to apply the updates and it ends up eventually failing. 
`Package operation failed
The installation or removal of a software package failed.`

Also a separate window appears says
`System program problem detected
Do you want to report the problem now?`

**Comment by lag-linaro** [comment] 2019-09-03 06:27
You are using the old image.  Where are you getting that from?

**Comment by lag-linaro** [comment] 2019-09-03 06:36
Could you please re-download the latest image and send me the `md5sum` of it?

**Comment by dmelgar** [comment] 2019-09-03 16:01
Where did it come from?
https://github.com/aarch64-laptops/build
Then in section https://github.com/aarch64-laptops/build#use-an-existing-pre-built-image
It says, `Download THIS IMAGE `
Which links to
http://releases.linaro.org/aarch64-laptops/images/ubuntu/18.04/aarch64-laptops-bionic-prebuilt.img.xz

The xz I was using has an md5 of 
`b3c38c31e0a300674feddd26f54f12a2  aarch64-laptops-bionic-prebuilt.img.xz`
`-rw-r--r-- 1 pi pi 1532887432 Sep  1 13:58 aarch64-laptops-bionic-prebuilt.img.xz`
Was downloaded September 1st from Github link above.

Redownloading today...
`3b128cb45d5996a5f34ff53f055d34fd  aarch64-laptops-bionic-prebuilt.img (1).xz`

**Comment by dmelgar** [comment] 2019-09-03 16:29
WIth the newly downloaded image today, touchpad is working! Woot!

**Comment by lag-linaro** [comment] 2019-09-04 08:52
Great, thanks for testing.
